[package]
name = "rust_mixer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wav="1.0.0"
json="0.12.4"
rayon = "1.5.3"